<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<TargetFrameworks>netstandard2.0;netstandard2.1;net5.0;net6.0;net7.0;net8.0</TargetFrameworks>
	<RootNamespace>DrMock.EFCore</RootNamespace>
	<GenerateDocumentationFile>True</GenerateDocumentationFile>
	<PackageId>DrMock.EFCore</PackageId>
	<Authors>Jeph Bayfield</Authors>
	<Product>DrMock.EFCore</Product>
	<Title>DrMock.EFCore</Title>
	<Description>A Superset of Moq which allows quick, easy and clear testing with Entity Framework Core (Base Interface only)</Description>
	<Copyright>2026 jephbayf1986</Copyright>
	<PackageProjectUrl></PackageProjectUrl>
	<RepositoryUrl>https://github.com/jephbayf1986/DrMock.EntityFrameworkCore</RepositoryUrl>
	<PackageTags>Database;Testing;C#</PackageTags>
	<PackageReleaseNotes>Add further pathways for Exists</PackageReleaseNotes>
	<NeutralLanguage>en</NeutralLanguage>
	<PackageLicenseExpression>MIT</PackageLicenseExpression>
	<PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
	<PackageReadmeFile>README.md</PackageReadmeFile>
	<Company>jephbayf1986</Company>
	<Version>1.0.2</Version>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="MockIDbContext.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="dotRandom" Version="1.0.2" />
    <PackageReference Include="DrMock.EFCore.Base" Version="1.0.1" />
    <PackageReference Include="Moq" Version="4.20.72" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
	<PackageReference Include="Microsoft.EntityFrameworkCore" Version="3.1.*" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.1'">
	<PackageReference Include="Microsoft.EntityFrameworkCore" Version="3.*" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net5.0'">
	<PackageReference Include="Microsoft.EntityFrameworkCore" Version="5.*" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net6.0'">
	<PackageReference Include="Microsoft.EntityFrameworkCore" Version="6.*" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net7.0'">
	<PackageReference Include="Microsoft.EntityFrameworkCore" Version="7.*" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net8.0'">
	<PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.*" />
  </ItemGroup>
	
  <ItemGroup Condition="'$(TargetFramework)' == 'net9.0'">
	<PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.*" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net10.0'">
	<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.*" />
  </ItemGroup>

  <ItemGroup>
	<None Include="..\..\README.md">
	  <Pack>True</Pack>
	  <PackagePath>\</PackagePath>
	</None>
  </ItemGroup>

</Project>
